### ISSUE TITLE
ZTest.setup() function does not runs

### ISSUE THREAD

**Issue by chuongddh** [linkedin/Zopkio#102] opened 2015-12-14 21:07 UTC
Hello there,

I create my new test with ZTestSuite and ZTest object. In my ZTest class, I specifies some behavior for setup() function. However, it does not run at Zopkio runtime. Is there any setting I have to change to use setup() function?

Thanks and Regards,
Chuong

**Comment by arpras** [comment] 2015-12-15 01:19
Hi Chuong,

I am looking at this issue now.

Thanks

**Comment by arpras** [comment] 2015-12-15 22:36
Where are you placing the setup() and teardown() functions ? It needs to be as part of ZtestSuite object (where you place the setup_suite() and teardown_suite().

I believe this was not indicated clearly in the Ztest class. I am fixing it in the latest pull request. 

Please let me know if putting it as part of Ztestsuite fixes the issue.

**Comment by chuongddh** [comment] 2015-12-16 18:13
HI Arpras,

Thank you for providing the fix. I have setup() and teardown() function in
my ZTest class similar to the Ztest.py. I saw your change that move these
function into ZTestSuite class.

However, in my opinion, these function should be in ZTest class itself;
because each test case or ztest object may have different setup steps and
teardown process. We actually have that exact requirements here at PubNub.

Therefore, it would be great that Zopkio can support these function in
ZTest as original ZTest.py code :).

Thanks and Regards,
Chuong

**Comment by jdehrlich** [comment] 2015-12-16 20:56
I agree with Chuong, I looked briefly at the code and see where the issue is. This was a flaw in my original implementation and will work on adding support
Joshua

**Comment by chuongddh** [comment] 2015-12-16 22:29
Thank you Joshua, I appreciate your support.

**Comment by arpras** [comment] 2015-12-16 23:26
Thanks Josh. Please send over a pull request when ready :+1:

**Comment by arpras** [comment] 2016-01-03 03:10
Pull request merged. Closing.

**Closed by arpras** 2016-01-03 03:10 UTC
